Consistent naming of Windows server releases
chef/chef-web-docs pull request #1410
Opened 2018-05-08 19:32 UTC by tas50

2018-05-09 16:14 UTC, brewn commented
In general I see these versions used with a space between them, ie. `2012 R2`. Is there a reason to omit the space?

2018-05-09 16:14 UTC, stuartpreston approved these changes

2018-05-09 16:15 UTC, stuartpreston requested changes
Can we just keep the uppercase version with the spaces (i.e. '2008 R2', '2012 R2')

2018-05-11 16:44 UTC, stuartpreston approved these changes

2018-05-11 21:14 UTC, merged