WIP: Improe custom resources docs
chef/chef-web-docs pull request #151
Opened 2016-10-13 09:01 UTC by tas50

This is a WIP to improve our custom resources docs so we can get more users utilizing custom resources.

2016-10-14 10:56 UTC, thommay requested changes

2016-10-14 10:56 UTC, thommay commented on includes_custom_resources/includes_custom_resources_syntax.rst
> +The syntax for a basic custom resource utilizing built-in chef resources is. For example:
I think we should make it clear that you can use ruby here, and it's safe to do so directly and that chef will take care of running it at the correct time.

2016-10-14 10:56 UTC, thommay commented on includes_custom_resources/includes_custom_resources_syntax.rst
> +where the first action listed is the default action.
I kind of think we should just teach people to be explicit about the default action.

2016-10-14 10:56 UTC, thommay commented on includes_custom_resources/includes_custom_resources.rst
> +A method of extending of |chef| to create your own custom resources that help to automate common patterns used in your cookbooks.
Lose the second "of". This definition seems rather circular too.

2016-11-14 22:06 UTC, closed without merging

2016-11-14 22:06 UTC, tas50 commented
Closing this out to fix it in smaller bits