Don't call knife windows a plugin
chef/chef-web-docs pull request #1650
Opened 2018-09-20 18:33 UTC by tas50

While technically true it ships in DK so no one outside Chef needs to know it's a plugin.

2018-09-20 19:24 UTC, stuartpreston requested changes
Also, we provide a Chocolatey package that should be documented: https://chocolatey.org/packages/chef-client

2018-09-20 19:24 UTC, stuartpreston commented on chef_master/source/install_windows.rst
> +* By using the `knife windows </plugin_knife_windows.html>`__ to bootstrap the chef-client; this process requires the target node be available via SSH (port 22) or by using the HTTP or HTTPS ports th
Grammar: We should also remove the "the" before the link too.

2018-09-20 19:24 UTC, stuartpreston commented on chef_master/source/install_windows.rst
> +* By using the `knife windows </plugin_knife_windows.html>`__ to bootstrap the chef-client; this process requires the target node be available via SSH (port 22) or by using the HTTP or HTTPS ports th
Replace: "via SSH (port 22) or by using the HTTP or HTTPS ports that are required by WinRM" with "via the WinRM port (typically port 5985)" or similar.

2018-09-20 19:30 UTC, tas50 commented
I totally missed that SSH reference. Thanks @stuartpreston

2018-09-21 12:53 UTC, stuartpreston approved these changes

2018-09-21 20:24 UTC, tas50 commented
@mjingle Can we merge this one?

2018-09-24 13:43 UTC, mjingle commented
@tas50 We will. I didn't know if Stuart's comment about documenting a Chocolatey package was included on this PR or not. Making a card to follow-up on that later.

2018-09-24 15:29 UTC, merged