Updates knife_windows docs
chef/chef-web-docs pull request #1729
Opened 2018-10-24 22:46 UTC by kagarmoe

Signed-off-by: kagarmoe <kgarmoe@chef.io>

### Description

Errs on the side of over-completion.

Updates to the:
[ ] bootstrap_windows_ssh 
[ ] bootstrap_windows_winrm

### Definition of Done

### Issues Resolved

[List any existing issues this PR resolves, or any Discourse or
StackOverflow discussion that's relevant]

### Check List

- [ ] Spell Check
- [ ] Local build
- [ ] Examine the local build
- [ ] All tests pass

2018-10-24 22:50 UTC, tas50 commented
Looks like we were missing a few things there...

2018-10-30 18:45 UTC, mwrock requested changes
This is MUCH BETTER!

2018-10-30 18:45 UTC, mwrock commented on chef_master/source/knife_windows.rst
> +    The maximum time in minutes to wait to for authentication over the transport to the node to succeed. Default: ``2``.
`to wait to for` -> `to wait for`

2018-10-30 18:45 UTC, mwrock commented on chef_master/source/knife_windows.rst
> +``--[no]host-key-verify``
should this be `[no-]` with a tailing dash?

2018-10-30 18:45 UTC, mwrock commented on chef_master/source/knife_windows.rst
> +    Use to disable host key verification. Default: ``true``.
This description assumes that `no-` was specified and it should probably read `Use to enable`

2018-10-30 18:45 UTC, mwrock commented on chef_master/source/knife_windows.rst
> +    Verify the SSL cert for HTTPS requests to the Chef sAPI. Default: ``true``.
I think this is `chef server` instead of `chef api`

2018-10-30 18:45 UTC, mwrock commented on chef_master/source/knife_windows.rst
> +    QUERY is a space-separated list of servers.
Just `A space-separated list of servers`

2018-10-30 18:50 UTC, mwrock commented on chef_master/source/knife_windows.rst
> +    The SSH username. Default: ``root``.
The WinRM username. Default: `Administrator`

2018-10-30 18:51 UTC, mwrock commented on chef_master/source/knife_windows.rst
> +``-x USERNAME``, ``--ssh-user USERNAME``
`--winrm-user`

2018-10-30 19:17 UTC, mwrock approved these changes

2018-10-31 18:22 UTC, merged