Note 12.18.14 berks/chefdk compatibility reqs
chef/chef-web-docs pull request #1779
Opened 2018-12-03 21:38 UTC by moutons

The API version bump introduces an incompatibility with older versions of Berkshelf, which means that Berkshelf >= 7.0.5 and ChefDK >= 3.2.30 should be used.

Signed-off-by: Shaun Mouton <smouton@chef.io>

### Description

This change documents a potential issue users may experience when using older versions of Berkshelf to upload cookbooks to Chef Server version 12.18.14

### Definition of Done

### Issues Resolved

### Check List

- [ ] Spell Check
- [ ] Local build
- [ ] Examine the local build
- [ ] All tests pass

2018-12-04 00:29 UTC, kagarmoe reviewed
@mjingle Could you take a pass at this, too?

2018-12-04 00:30 UTC, kagarmoe commented on chef_master/source/release_notes_server.rst
> +.. note:: The API version bump introduces an incompatibility with older versions of Berkshelf, which means that Berkshelf >= 7.0.5 and ChefDK >= 3.2.30 should be used. If your Berkshelf uploads to Ch
```suggestion
.. note:: Chef Server 12.18.14 introduces an incompatibility between older versions of Berkshelf and the ChefDK. We recommend using the minimum versions of  Berkshelf >= 7.0.5 and ChefDK >= 3.2.30. 
A Berkshelf upload to Chef Server failing with ``Net::HTTPServerException: 400 "Bad Request"`` and opscode-erchef logs containing ``status=400`` and ``req_api_version=1`` in the log line for the related cookbook upload API request, are strong evidence of this incompatibility.
```

2018-12-04 17:55 UTC, kagarmoe requested changes
Edit for clarity.

2018-12-04 17:55 UTC, kagarmoe commented on chef_master/source/release_notes_server.rst
> +A Berkshelf upload to Chef Server failing with ``Net::HTTPServerException: 400 "Bad Request"`` and opscode-erchef logs containing ``status=400`` and ``req_api_version=1`` in the log line for the rela
```suggestion
This incompatibility manifests with a Berkshelf upload to Chef Server failure of ``Net::HTTPServerException: 400 "Bad Request"`` and opscode-erchef logs containing ``status=400`` and ``req_api_version=1`` in the log line for the corresponding cookbook upload API request.
```

2018-12-05 18:47 UTC, moutons commented
closing the PR from my fork in favor of a PR from the chef org so expeditor's happier

2018-12-05 18:47 UTC, closed without merging

2018-12-05 18:52 UTC, moutons commented
#1780 is the new PR