Update config_rb_server_optional_settings.rst
chef/chef-web-docs pull request #2019
Opened 2019-07-10 19:12 UTC by trickyearlobe

### Description

Documents optional ```data_collector['health_check']``` setting added to ```chef-server.rb``` by PR1704.

### Issues/PR's Resolved

https://github.com/chef/chef-server/issues/1703
https://github.com/chef/chef-server/pull/1704

### Check List

- [ ] Spell Check
- [ ] Local build
- [ ] Examine the local build
- [ ] All tests pass

2019-07-10 23:38 UTC, irvingpop commented
This should be merged after referenced PR is merged _and_ a new chef-server release is promoted to stable

2019-07-10 23:38 UTC, irvingpop approved these changes

2019-08-09 19:20 UTC, mjingle commented
@trickyearlobe Hi! I noticed there was some movement on https://github.com/chef/chef-server/pull/1704. Please let us know if the documentation still matches what was implemented. Thank you in advance!

2019-08-09 20:14 UTC, tas50 commented
The PR was merged, but the release hasn't been made yet.

2019-08-12 12:44 UTC, trickyearlobe commented
But to answer @mjingle question, yes, the doc updates still match the PR content that was merged, but not yet released.

2019-09-19 19:56 UTC, kagarmoe commented
Hi @trickyearlobe ! Was this code merged?

2019-11-01 19:43 UTC, trickyearlobe commented
@kagarmoe , yes, its shipped in 13.0.47

2019-11-05 23:41 UTC, IanMadd requested changes
I changed ``false`` to ``true`` and updated the other text to make it a bit more clear. Let me know what you think @trickyearlobe.

2019-11-05 23:41 UTC, IanMadd commented on chef_master/source/config_rb_server_optional_settings.rst
> +   A boolean that controls whether the data collector health is included in the overall health at the ``_status`` endpoint. This setting when set to ``false`` is useful to prevent perfectly healthy f
```suggestion
   A boolean that controls whether the data collector health is included in the overall health at the ``_status`` endpoint. When set to ``true``, Chef Infra Server will report that healthy front end Chef HA cluster members have failed when the `data_collector['root_url']`` cannot be reached. As a result, the load balancer will remove those members from the load balancer pool. Default value: ``true``.
```

2019-11-11 09:47 UTC, trickyearlobe commented on chef_master/source/config_rb_server_optional_settings.rst
> +   A boolean that controls whether the data collector health is included in the overall health at the ``_status`` endpoint. This setting when set to ``false`` is useful to prevent perfectly healthy f
Looks great, ship it ;-)

2019-11-12 17:13 UTC, IanMadd approved these changes

2019-11-12 17:13 UTC, merged