Update config_rb_server.rst
chef/chef-web-docs pull request #2085
Opened 2019-08-21 19:16 UTC by lbakerchef

``postgresql['sslmode']``
	SSL encryption mode between Chef Server and PostgreSQL.  Valid settings are 'disable' (off) and 'require' (on).  Default value: 'disable'.

2019-08-21 20:09 UTC, IanMadd commented
Hi @lbakerchef, can you add your [DCO sign-off ](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco) to this PR. Thanks!

2019-11-19 22:53 UTC, PrajaktaPurohit approved these changes
Can be merged after Chef-server 13.1.x is released.

2019-11-23 01:35 UTC, markan requested changes
Are there any configuration values that affect what SSL keys chef-server trusts (I suspect we've added some functionality around that as part of our general hardening effort on internal service calls).
If those exist, we should document them.

2019-11-25 18:30 UTC, markan approved these changes
Looks reasonable, but I might consider whether the SSL postgres options need to be documented in the performance tuning section or not.

2019-11-25 21:53 UTC, PrajaktaPurohit commented
@markan Adding https://github.com/chef/chef-server/issues/1850 to capture some of your input.

2019-12-04 20:38 UTC, lbakerchef commented
Good catch on the performance tuning section.  Can't remember the rationale for why that was put there.

2020-01-13 23:03 UTC, IanMadd commented on chef_master/source/config_rb_server.rst
> +   SSL encryption mode between Chef Server and PostgreSQL.  Valid settings are ``'disable'`` (off) and ``'require'`` (on).  Default value: ``'disable'``.
```suggestion
   SSL encryption mode between the Chef Infra Server and PostgreSQL.  Valid settings are ``'disable'`` and ``'require'``.  Default value: ``'disable'``. 
```

2020-01-22 20:16 UTC, merged