Update style_guide for Hugo/markdown
chef/chef-web-docs pull request #2093
Opened 2019-08-28 20:46 UTC by IanMadd

Signed-off-by: IanMadd <imaddaus@chef.io>

### Description

This rewrites the Style Guide for Markdown and Hugo.

### Check List

- [ ] Spell Check
- [X] Local build
- [X] Examine the local build
- [ ] All tests pass

2019-08-28 21:25 UTC, kagarmoe requested changes

2019-08-28 21:25 UTC, kagarmoe commented on content/style_guide.md
> +The convention we've adopted is to use the identifier of the page's parent, followed by a forward slash, then the page file, a space, and then the page title.
An example might be helpful

2019-08-28 21:25 UTC, kagarmoe commented on content/style_guide.md
> +    1. text goes here
Can we use:
1.
1.
1.

& Hugo generates the numbers? That is preferable to maintaining numbered lists.

2019-08-28 21:25 UTC, kagarmoe commented on content/style_guide.md
> +    </table>
Even though Hugo can handle HTML tables, I'd prefer to limit us to markdown tables in the docs, in order to keep the pages as single-language as possible.

2019-08-28 21:25 UTC, kagarmoe commented on content/style_guide.md
> +External links requires an HTTP address.
```suggestion
External links require an HTTP address.
```

2019-08-28 21:25 UTC, kagarmoe commented on content/style_guide.md
Does Hugo support code blocks for `powershell`  and `=`output `?

2019-08-28 21:25 UTC, kagarmoe commented on content/style_guide.md
> +Shortcodes
Perhaps we should call this "Reusing text" or something similar? Shortcodes have different uses (as you well know :-) ) and we don't want to mislead our readers.

2019-08-28 21:25 UTC, kagarmoe commented on content/style_guide.md
>  Images should be 96 dpi and no larger than 600 pixels wide. Ideally, no
We should choose between 600 & 550px width. We should also figure out how to lint image widths.

2019-08-28 21:25 UTC, kagarmoe commented on content/style_guide.md
>  -   `Chef Automate` for the Chef Automate product
Chef Automate
Chef Habitat
Chef Infra (formerly Chef)
Chef Infra Client (Use Chef Client up to version 14.x)
Chef Infra Server (Formerly Chef Server)
Chef InSpec

2019-08-28 21:25 UTC, kagarmoe commented on content/style_guide.md
> -TOC Trees
Do we need to add pages manually to the sitemap.xml or the index.html?

2019-08-29 13:45 UTC, IanMadd commented on content/style_guide.md
> -TOC Trees
There is no sitemap, but we do have pages listed in the _index.md.

2019-08-29 13:53 UTC, IanMadd commented on content/style_guide.md
> +Shortcodes
"Recurring text blocks" or "Repeating text blocks"?

2019-08-29 14:02 UTC, IanMadd commented on content/style_guide.md
> +    1. text goes here
yup

2019-08-29 14:15 UTC, IanMadd commented on content/style_guide.md
Here's the docs on [syntax highlighting](https://gohugo.io/content-management/syntax-highlighting/)
So, yes on powershell.
I'm not sure how you want an output to look, but there is an option to highlight certain lines with a different color using the `hi_lines` option.

2019-08-29 17:47 UTC, IanMadd commented on content/style_guide.md
>  Images should be 96 dpi and no larger than 600 pixels wide. Ideally, no
I haven't found a way in Hugo to lint images. Maybe we could add something to the makefile?

2019-08-29 19:13 UTC, IanMadd commented on content/style_guide.md
> +Shortcodes
I replaced this with `Repeating Text Blocks`

2019-08-29 19:14 UTC, IanMadd commented on content/style_guide.md
> +    </table>
I removed the html tables.

2019-09-05 21:16 UTC, kagarmoe approved these changes
Resolve the merge conflict & you're good to go!

2019-09-06 18:18 UTC, schisamo approved these changes

2019-09-06 19:03 UTC, merged