update links to other docs in index.html
chef/chef-web-docs pull request #2125
Opened 2019-09-17 19:19 UTC by IanMadd

Signed-off-by: IanMadd <imaddaus@chef.io>

### Description

This updates the list of Chef documentation and their links on the index page. 

### Check List

- [ ] Spell Check
- [X] Local build
- [X] Examine the local build
- [ ] All tests pass

2019-09-17 20:00 UTC, mjingle approved these changes
![tenor-209643958](https://user-images.githubusercontent.com/5807053/65075132-47702680-d964-11e9-8df8-b9571597eb2f.gif)

2019-09-17 20:16 UTC, kagarmoe requested changes

2019-09-17 20:16 UTC, kagarmoe commented on chef_master/source/index.rst
> +* Legacy Chef Automate 1
```suggestion
* Chef Automate 1.0 (deprecated)
```

2019-09-17 20:16 UTC, kagarmoe commented on chef_master/source/index.rst
> +For information on Chef Automate 2, Chef Habitat, Chef InSpec, and Chef Workstation, see their respective documentation:
```suggestion
Documentation for other Chef products: 
```

2019-09-17 20:16 UTC, kagarmoe commented on chef_master/source/index.rst
> +* `Chef Automate 2 documentation <https://automate.chef.io/docs/quickstart/>`_
```suggestion
* `Chef Automate 2.0 <https://automate.chef.io/docs/quickstart/>`_
```

2019-09-17 20:16 UTC, kagarmoe commented on chef_master/source/index.rst
>  * `Chef Habitat documentation <https://www.habitat.sh/docs/>`_
```suggestion
* `Chef Habitat <https://www.habitat.sh/docs/>`_
```

2019-09-17 20:16 UTC, kagarmoe commented on chef_master/source/index.rst
>  * `Chef InSpec documentation <https://www.inspec.io/docs/>`_
```suggestion
* `Chef InSpec <https://www.inspec.io/docs/>`_
```

2019-09-17 20:16 UTC, kagarmoe commented on chef_master/source/index.rst
> +* `Chef Workstation documentation <https://www.chef.sh/docs/chef-workstation/getting-started/>`_
```suggestion
* `Chef Workstation <https://www.chef.sh/docs/chef-workstation/getting-started/>`_
```

2019-09-18 17:33 UTC, kagarmoe approved these changes

2019-09-18 17:41 UTC, merged