Quick rework of the attributes doc to mention Policyfiles
chef/chef-web-docs pull request #2133
Opened 2019-09-18 17:43 UTC by tas50

There was no mention of Policyfiles in our attributes page, which is unfortunate since we're directing folks to Policyfiles now.

Signed-off-by: Tim Smith <tsmith@chef.io>

2019-09-18 21:19 UTC, IanMadd requested changes

2019-09-18 21:19 UTC, IanMadd commented on chef_master/source/attributes.rst
> +* Many attributes are maintained in the chef-repo for policyfiles, environments, roles, and cookbooks (attribute files and recipes)
```suggestion
* Many attributes are maintained in the chef-repo for Policyfiles, environments, roles, and cookbooks (attribute files and recipes)
```

2019-09-18 21:19 UTC, IanMadd commented on chef_master/source/attributes.rst
> +The list of automatic attributes that are collected by Ohai at the start of each Chef Infra Client run vary from organization to organization, and will often vary between the various server types bei
```suggestion
Ohai collects a list of automatic attributes at the start of each Chef Infra Client run. This list will vary from organization to organization, by server type, and by the platform that runs those servers. All the attributes collected by Ohai are unmodifiable by Chef Infra Client. Run the ``ohai`` command on a system to see which automatic attributes Ohai has collected for a particular node.
```

2019-09-18 21:19 UTC, IanMadd commented on chef_master/source/ohai.rst
> +The list of automatic attributes that are collected by Ohai at the start of each Chef Infra Client run vary from organization to organization, and will often vary between the various server types bei
```suggestion
Ohai collects a list of automatic attributes at the start of each Chef Infra Client run. This list will vary from organization to organization, by server type, and by the platform that runs those servers. All the attributes collected by Ohai are unmodifiable by Chef Infra Client. Run the ``ohai`` command on a system to see which automatic attributes Ohai has collected for a particular node.
```

2019-09-18 21:19 UTC, IanMadd commented on chef_master/source/attributes.rst
> +At the beginning of a Chef Infra Client run, all attributes except for normal attributes are reset. Chef Infra Client rebuilds them using automatic attributes collected by Ohai at the beginning of ea
```suggestion
All attributes except for normal attributes are reset at the beginning of a Chef Infra Client run. Chef Infra Client rebuilds these attributes using automatic attributes collected by Ohai at the beginning of each Chef Infra Client run, and then uses default and override attributes that are specified in cookbooks, roles, environments, and Policyfiles. All attributes are then merged and applied to the node according to attribute precedence. The attributes that were applied to the node are saved to the Chef Infra Server as part of the node object at the conclusion of each Chef Infra Client run.
```

2019-09-18 21:19 UTC, IanMadd commented on chef_master/source/attributes.rst
>  * Removed for a specific, named attribute precedence level
```suggestion
* Removed for a specific, named attribute precedence level.
```

2019-09-18 21:19 UTC, IanMadd commented on chef_master/source/attributes.rst
>  * Removed for all attribute precedence levels
```suggestion
* Removed for all attribute precedence levels.
```

2019-09-18 21:19 UTC, IanMadd commented on chef_master/source/attributes.rst
>  * Fully assigned attributes
```suggestion
* Fully assigned attributes.
```

2019-09-18 21:19 UTC, IanMadd commented on chef_master/source/attributes.rst
> +* Data about the node collected by `[Ohai] </ohai.html>`__
```suggestion
* Data about the node collected by `[Ohai] </ohai.html>`__.
```

2019-09-18 21:19 UTC, IanMadd commented on chef_master/source/attributes.rst
>  * The node object that was saved to the Chef Infra Server at the end of the previous Chef Infra Client run
```suggestion
* The node object that was saved to the Chef Infra Server at the end of the previous Chef Infra Client run.
```

2019-09-18 21:19 UTC, IanMadd commented on chef_master/source/attributes.rst
>  * The rebuilt node object from the current Chef Infra Client run, after it is updated for changes to cookbooks (attribute files and/or recipes), roles, and/or environments, and updated for any change
```suggestion
* The rebuilt node object from the current Chef Infra Client run, after it is updated for changes to cookbooks (attribute files and/or recipes), roles, and/or environments, and updated for any changes to the state of the node itself.
```

2019-09-24 17:22 UTC, lamont-granquist approved these changes

2019-09-24 17:22 UTC, merged