Update resources for Chef Infra Client 15.5
chef/chef-web-docs pull request #2195
Opened 2019-11-15 23:24 UTC by tas50

windows_firewall profile takes an array, we have a new chef_sleep resource, and some typos are synced over.

Signed-off-by: Tim Smith <tsmith@chef.io>

2019-11-18 19:04 UTC, IanMadd requested changes

2019-11-18 19:04 UTC, IanMadd commented on chef_master/source/resource_chef_sleep.rst
> +Use the **chef_sleep** resource to set the number of seconds to sleep during a Chef Infra Client run. Only use this resource when a command or service exits successfully but is not ready for the next
Is it fair to say that it will pause an Infra Client run?

```suggestion
The **chef_sleep** resource will pause a Chef Infra Client run for a set number of seconds. Only use this resource when a command or service exits successfully but is not ready for the next step of the recipe.
```

2019-11-18 19:04 UTC, IanMadd commented on chef_master/source/resource_chef_sleep.rst
> +   Sleep the Chef Infra Client run for a specified number of seconds
```suggestion
   Pause the Chef Infra Client run for a specified number of seconds.
```

2019-11-18 19:04 UTC, IanMadd commented on chef_master/source/resource_rhsm_errata_level.rst
> +Use the **rhsm_errata_level** resource to install all packages of a specified errata level from the Red Hat Subscription Manager. For example, you can ensure that all packages associated with errata
Did you intend for these to be backticks? ``Critical``?

2019-11-18 19:04 UTC, IanMadd commented on chef_master/source/resource_windows_package.rst
> +   If the source package to install is at a remote location this property allows you to define a hash of properties and their value which will be used by the underlying remote_file resource, which fe
```suggestion
   This property allows you to define a hash of properties and their value if the source package to be installed is at a remote location. This hash will be used by the underlying **remote_file** resource which will fetch the source package.
```

2019-11-18 19:19 UTC, tas50 commented on chef_master/source/resource_rhsm_errata_level.rst
> +Use the **rhsm_errata_level** resource to install all packages of a specified errata level from the Red Hat Subscription Manager. For example, you can ensure that all packages associated with errata
This is right out of the source code so no backticks there

2019-11-19 17:12 UTC, IanMadd approved these changes

2019-11-19 17:14 UTC, merged