Document use of "chef-client -j file.json" passed attributes
chef/chef-web-docs pull request #2201
Opened 2019-11-27 22:37 UTC by mattray

Attributes passed via "chef-client -j file.json" were poorly documented, this attempts to fill in the gaps for how they are applied, their precedence and their persistence.

2019-11-27 22:53 UTC, lamont-granquist approved these changes

2019-12-06 01:37 UTC, IanMadd requested changes
Suggestions to improve grammar, punctuation, and clarity.

2019-12-06 01:37 UTC, IanMadd commented on chef_master/source/attributes.rst
> +* Chef Infra Client will pull down the node object from the Chef Infra Server (which contains the attribute data from the previous Chef Infra Client run, including those set via ``-j`` with JSON file
```suggestion
* Chef Infra Client will pull down the node object from the Chef Infra Server and then reset all the attributes except ``normal``. The node object will contain the attribute data from the previous Chef Infra Client run including attributes set with JSON files via ``-j``.
```

2019-12-06 01:37 UTC, IanMadd commented on chef_master/source/ctl_chef_client.rst
> +   The path to a file that contains JSON data. Used to setup the first client run. **For all the future runs with option -j the attributes are expected to be persisted in the chef-server.**
```suggestion
   The path to a file that contains JSON data. Used to setup the first client run. The attributes will persist on the Chef Infra Server for all future runs with option ``-j``.
```

2019-12-10 20:20 UTC, IanMadd approved these changes

2019-12-10 20:20 UTC, merged