Update Chef Infra Server Release Notes for 13.1.13
chef/chef-web-docs pull request #2204
Opened 2019-12-05 16:55 UTC by OBrienCommaJosh

### Description

This updates release notes documentation for Chef Infra Server version 13.1.13

### Definition of Done

Documentation accurately portrays information from [release announcement in discourse](https://discourse.chef.io/t/chef-infra-server-13-1-13-released/16282).

### Check List

- [ ] Spell Check
- [ ] Local build
- [ ] Examine the local build
- [ ] All tests pass

2019-12-05 20:44 UTC, IanMadd requested changes
General suggestions on content, grammar, punctuation

2019-12-05 20:44 UTC, IanMadd commented on chef_master/source/release_notes_server.rst
> + * Add AWS to known platforms
RST requires a space before a nested bullet point item
```suggestion

 * Add AWS to known platforms
```

2019-12-05 20:44 UTC, IanMadd commented on chef_master/source/release_notes_server.rst
> +* ``_status`` endpoint reports healthy even if ``data_collector`` is down not causing unnecessary failovers
```suggestion
* The ``_status`` endpoint now reports healthy even if the ``data_collector`` is down which will no longer cause unnecessary failovers.
```

2019-12-05 20:44 UTC, IanMadd commented on chef_master/source/release_notes_server.rst
> +* ``chef-server-ctl`` is no longer installed in the user path only the appbundled version is installed in the user path
```suggestion
* ``chef-server-ctl`` is no longer installed in the user path. Now only the appbundled version is installed in the user path.
```

2019-12-05 20:44 UTC, IanMadd commented on chef_master/source/release_notes_server.rst
> +* Data collector proxy-header X-Forwarded for is set as expected
```suggestion
* Data collector proxy-header X-Forwarded is set as expected.
```

2019-12-05 20:44 UTC, IanMadd commented on chef_master/source/release_notes_server.rst
> +* Fixes issue with Chef Support Zendesk sign-ins when a first name is not set in Hosted Chef
```suggestion
* Fixed an issue with Chef Support Zendesk sign-ins when a first name is not set in Hosted Chef.
```

2019-12-05 20:44 UTC, IanMadd commented on chef_master/source/release_notes_server.rst
> +* Added support for running the Chef Infra Server on Red Hat Enterprise Linux 8
```suggestion
* Added support for running the Chef Infra Server on Red Hat Enterprise Linux 8.
```

2019-12-05 20:44 UTC, IanMadd commented on chef_master/source/release_notes_server.rst
> +* Improvements to ``chef-server-ctl gather-logs``
```suggestion
* ``chef-server-ctl gather-logs`` was updated with the following improvements:
```

2019-12-05 20:44 UTC, IanMadd commented on chef_master/source/release_notes_server.rst
> +* SLES 11 is no longer supported per our [platform policy](https://docs.chef.io/platforms.html#platform-end-of-life-policy), as upstream support ended in March of this year.
```suggestion
* SLES 11 is no longer supported per our `platform policy <https://docs.chef.io/platforms.html#platform-end-of-life-policy>`_, as upstream support ended in March of this year.
```

2019-12-05 23:34 UTC, IanMadd commented
Hi @OBrienCommaJosh  can you add your DCO signoff. Thanks!

2019-12-06 16:46 UTC, OBrienCommaJosh commented
Sorry @IanMadd! Added!

2019-12-06 22:52 UTC, IanMadd approved these changes

2019-12-06 22:52 UTC, merged