Replace chef-server with infra-server
chef/chef-web-docs pull request #2400
Opened 2020-03-24 21:30 UTC by IanMadd

Signed-off-by: IanMadd <imaddaus@chef.io>

### Description

Replace `chef-server` with `infra-server`.

See also chef/automate#3181

### Definition of Done

### Issues Resolved

chef/automate#3176

### Check List

- [ ] Spell Check
- [ ] Local build
- [ ] Examine the local build
- [ ] All tests pass

2020-03-25 17:28 UTC, kagarmoe requested changes

2020-03-25 17:28 UTC, kagarmoe commented on content/install_bootstrap.md
> +10.0.0.6    infra-server chef-server.automate.com
```suggestion
10.0.0.6    infra-server infra-server.automate.com
```

2020-03-25 17:41 UTC, btm approved these changes

2020-03-26 16:51 UTC, kagarmoe approved these changes

2020-03-26 17:33 UTC, merged