WIP Preview InSpec docs
chef/chef-web-docs pull request #2555
Opened 2020-06-24 17:38 UTC by IanMadd

### Description

Preview InSpec docs in docs.chef.io

### Definition of Done

### Issues Resolved

[List any existing issues this PR resolves, or any Discourse or
StackOverflow discussion that's relevant]

### Check List

- [ ] Spell Check
- [ ] Local build
- [ ] Examine the local build
- [ ] All tests pass

2020-06-24 19:09 UTC, kagarmoe requested changes
Looks good! Left a suggestion for handling the OS resources explanation

2020-06-24 19:09 UTC, kagarmoe commented on content/inspec/resources/_index.md
> +## OS
```suggestion
## Linux and Windows Resources
The following resources work on both Linux and Windows operating systems.
```

2020-06-24 19:09 UTC, kagarmoe commented on content/inspec/resources/_index.md
> +### Linux
```suggestion
### Linux
The following resources work on Linux operating systems.
```

2020-06-24 19:09 UTC, kagarmoe commented on content/inspec/resources/_index.md
> +### Windows
```suggestion
### Windows
The following resources work on Windows operating systems.
```

2020-07-16 23:04 UTC, IanMadd commented
See #2578

2020-07-16 23:04 UTC, closed without merging