Changed to reflect default cookbook generate behavior to policyfile
chef/chef-web-docs pull request #2600
Opened 2020-08-05 20:05 UTC by jasonnalewak

### Description

Correcting the cookbook generate doc to align with the default behavior of generating a policyfile instead of a berksfile

### Definition of Done

### Issues Resolved

None

2020-08-06 17:13 UTC, IanMadd commented
Hi @jasonnalewak, can you add your DCO signoff 
Thanks!
https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco

2020-08-06 22:30 UTC, kagarmoe commented on content/ctl_chef.md
> +:   Create a Berksfile in the cookbook. Default value: disabled. This value
```suggestion
:   Create a Berksfile in the cookbook. Default: disabled. 
```

2020-08-06 22:39 UTC, kagarmoe requested changes

2020-08-06 22:39 UTC, kagarmoe commented on content/ctl_chef.md
> +    must be specified to override the default creation of a policyfile
```suggestion
    Use to create a berksfile by overriding default creation of a Policyfile.
```

2020-08-06 22:39 UTC, kagarmoe commented on content/ctl_chef.md
> +    instead of a berksfile.
```suggestion
```

2020-08-06 22:39 UTC, kagarmoe commented on content/ctl_chef.md
> +    must be specified to override the default creation of a policyfile
Apologies if I messed with a required line length.

2020-08-06 22:39 UTC, kagarmoe commented on content/ctl_chef.md
>  :   Create a Policyfile in the cookbook instead of a Berksfile. Default
```suggestion
:   Create a Policyfile in the cookbook instead of a Berksfile.
```

2020-08-06 22:39 UTC, kagarmoe commented on content/ctl_chef.md
> +    value: enabled.
```suggestion
    Default: enabled.
```

2020-08-07 00:33 UTC, jasonnalewak commented
Sorry I'm not used to doing the DCO for commits.  I rebased the commits for the suggested changes to add the DCO sign offs.  If I broke the pipeline I'm sorry :(

2020-08-12 17:21 UTC, kagarmoe approved these changes
![tenor-249198068](https://user-images.githubusercontent.com/4400151/90046617-919d7d00-dc85-11ea-852c-453870b59494.gif)

2020-08-12 17:23 UTC, merged