Add automate docs
chef/chef-web-docs pull request #2611
Opened 2020-08-18 19:58 UTC by IanMadd

### Description

- Adds Automate docs to docs.chef.io
- Release Notes:
   - creates a new menu section for release notes
   - adds release notes for Automate
   - adds release notes for InSpec
   - migrates other release notes from Chef Infra menu section to the Release Notes section
- Updates Expeditor config for Automate
- Updates links in chef-web-docs to Automate docs
- Fixes a few menu links that changed when sites were consolidated to community.chef.io

### Definition of Done

### Issues Resolved

chef/release-engineering#1239

### Check List

- [ ] Spell Check
- [ ] Local build
- [ ] Examine the local build
- [ ] All tests pass

2020-08-18 20:02 UTC, kagarmoe commented
Waiting for the build...
![tenor-43401373](https://user-images.githubusercontent.com/4400151/90559800-0162aa80-e153-11ea-87ea-08822a4af9d8.gif)

2020-08-18 20:11 UTC, mjingle approved these changes
![tenor-168214626](https://user-images.githubusercontent.com/5807053/90560599-58757900-e16d-11ea-9a78-1b97eefbf2bd.gif)

2020-08-18 20:36 UTC, kagarmoe approved these changes
![tenor-183265689](https://user-images.githubusercontent.com/4400151/90562930-df1f5b80-e157-11ea-8256-5182b38ddc91.gif)

2020-08-18 21:23 UTC, schisamo requested changes

2020-08-18 21:23 UTC, schisamo commented on .expeditor/config.yml
> +  - workload: artifact_published:stable:automate:*
The "stable" channel for Automate is actually `current`. Additionally Automate does not promote an Omnibus package so the workload we need to subscribe to is slightly different:
```
# Subscribe to the promotion of the acceptance channel to current
workload: project_promoted:automate:acceptance:*
```

2020-08-19 14:06 UTC, schisamo approved these changes

2020-08-19 16:28 UTC, merged