confirmation of default interval and splay when using -d
chef/chef-web-docs pull request #3104
Opened 2021-04-30 15:09 UTC by JMccProgress

confirmation of default interval and splay when using -d    - change prompted by customer support ticket.

### Description

adds further information about the use of daemonized chef-client 

### Definition of Done

n/a

### Issues Resolved

this was prompted by customer support ticket 27499

### Check List

- [x] Spell Check
- [ ] Local build
- [ ] Examine the local build
- [ ] All tests pass

2021-04-30 17:12 UTC, IanMadd commented
Hi @JMccProgress, can you add your DCO signoff. 

https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco

2021-05-11 17:57 UTC, kagarmoe commented on content/ctl_chef_client.md
> +    If not otherwise set, this will also make use of the default `--interval`
```suggestion
    Left unset, the daemon uses the default `--interval` and `--splay` settings.
```

2021-05-11 17:58 UTC, kagarmoe requested changes
Small change.

2021-05-11 17:58 UTC, kagarmoe commented on content/ctl_chef_client.md
> +    and `--splay` values.
```suggestion
```

2021-08-10 22:13 UTC, kagarmoe approved these changes
![tenor-240764314](https://user-images.githubusercontent.com/4400151/128941770-2d723128-2db8-43cc-9ea7-5b117f1df8d7.gif)

2021-08-10 22:27 UTC, kagarmoe commented
Closed in favor of https://github.com/chef/chef-web-docs/pull/3324 (with DCO)

2021-08-10 22:27 UTC, closed without merging