[2673] Stop documenting using the chef_handler cookbook
chef/chef-web-docs pull request #3208
Opened 2021-06-07 13:22 UTC by damacus

## Description

The chef_handler cookbook has been deprecated for 3+ years and has been
included in chef infra client since 14.

## Issues Resolved

- Resolves #2673
- Resolves #2943
- 
Signed-off-by: Dan Webb <dan.webb@damacus.io>

## Check List

- [ ] Spell Check
- [ ] Local build
- [ ] Examine the local build
- [ ] All tests pass

2021-06-07 14:49 UTC, tas50 approved these changes

2021-06-10 19:39 UTC, tas50 commented on content/handlers.md
> +**chef_handler** resource. This resource is included with Chef 14 and above.
```suggestion
**chef_handler** resource. This resource is included with Chef Infra Client 14 and above.
```

2021-06-14 16:41 UTC, kagarmoe commented
We need to remove `chef_handler` from run lists and also `include_recipe 'chef_handler'`

2021-06-18 00:23 UTC, kagarmoe commented
How should we fix `handler_custom_example_cookbook_versions_recipe.md`?

2021-06-18 00:29 UTC, kagarmoe requested changes
How should we fix `handler_custom_example_cookbook_versions_recipe.md` shortcode? It is used one time in the docs. See it live: https://docs.chef.io/handlers/#defaultrb

2021-06-22 17:17 UTC, IanMadd commented
> How should we fix `handler_custom_example_cookbook_versions_recipe.md` shortcode? It is used one time in the docs. 

There are 8 shortcodes that start with "handler_custom" that are only used once. We might just yank them all and drop their text in the page: 

- handler_custom
- handler_custom_optional_interfaces
- handler_custom_interface_data
- handler_custom_interface_run_report_safely
- handler_custom_interface_run_report_unsafe
- handler_custom_object_run_status
- handler_custom_example_cookbook_versions
- handler_custom_example_cookbook_versions_recipe

There are also 5 shortcodes called with the readFile shortcode that are only used once:

- handler_custom_syntax.md
- handler_custom_interface_report.md
- handler_custom_example_cookbook_versions_handler.md
- handler_custom_example_json_file.md
- handler_custom_example_error_report.md

Maybe do this in another PR?

2021-06-23 08:37 UTC, damacus commented
@IanMadd yeah I was talking to Tim yesterday about that. I'll drop those short codes out in another PR. 

That handler page looks like it needs a rewrite anyway.

2021-06-23 20:40 UTC, kagarmoe commented
Rewriting the handler page can happen in another PR. I think we're OK to merge this one and then #3246. Agree?

2021-06-23 20:41 UTC, kagarmoe approved these changes
![tenor-93389720](https://user-images.githubusercontent.com/4400151/123165161-b9727b00-d428-11eb-87ff-07a22888e668.gif)

2021-06-23 20:54 UTC, IanMadd commented
My one issue is the headings converted from bold to H5 headings. Our style guide says we should use bold above an H4. 
https://docs.chef.io/style_markdown/#other-headings

2021-06-23 20:55 UTC, tas50 commented
@damacus this one is going to need a big rebase now that the shortcodes are merged

2021-06-24 12:38 UTC, tas50 commented on content/handlers.md
> +**chef_handler** resource. This resource is included with Chef 14 and above.
```suggestion
**chef_handler** resource. This resource is included with Chef Infra Client 14 and above.
```

2021-06-25 03:18 UTC, merged