Minor cleanup to the Windows page
chef/chef-web-docs pull request #330
Opened 2016-12-14 17:14 UTC by tas50

This page needs to be reworked heavily, but this removes a few things that were outdated.

Signed-off-by: Tim Smith <tsmith@chef.io>

2016-12-15 17:59 UTC, tas50 commented on chef_master/source/windows.rst
> +* Many community cookbooks on Supermarket provide Windows specific support. Chef maintains `PowerShell <https://github.com/chef-cookbooks/powershell>`_, `IIS <https://github.com/chef-cookbooks/iis>`_
I understand we can do better here. This whole section needs a rewrite. This is a step in the right direction though. Previously it sounded like we only had 4 Windows cookbooks.

2016-12-16 13:49 UTC, thommay requested changes

2016-12-16 13:49 UTC, thommay commented on chef_master/source/windows.rst
> +* Many community cookbooks on Supermarket provide Windows specific support. Chef maintains `PowerShell <https://github.com/chef-cookbooks/powershell>`_, `IIS <https://github.com/chef-cookbooks/iis>`_
needs a "the" after maintains, but definitely better.

2016-12-16 16:55 UTC, tas50 commented
I was thinking of the list as a non-definitive list, but I think that isn't coming across so I'll add 'the' there. In my mind our windows cookbook isn't 'the' windows cookbook. Someone else is more than welcome to make another one.

2016-12-16 20:35 UTC, davidwrede commented
@tas50 You're done iterating on this PR, correct? If so, I'll get it merged in shortly.

2016-12-16 22:42 UTC, tas50 commented
I'm done with this doc for now

2016-12-16 22:42 UTC, davidwrede commented
![gif-keyboard-4144949959141796710](https://cloud.githubusercontent.com/assets/1634752/21280923/ecd68cfc-c39d-11e6-9557-86d2d0dd6b5e.gif)

2016-12-16 22:43 UTC, merged