Updates Ohai Custom Resources
chef/chef-web-docs pull request #3329
Opened 2021-08-11 22:13 UTC by kagarmoe

Signed-off-by: kagarmoe <kgarmoe@chef.io>

## Description

[Please describe what this change achieves]

## Definition of Done

## Issues Resolved

[List any existing issues this PR resolves, or any Discourse or
StackOverflow discussion that's relevant]

## Related PRs

## Check List

- [ ] Spell Check
- [ ] Local build
- [ ] Examine the local build
- [ ] All tests pass

2021-08-11 22:44 UTC, teknofire approved these changes
Looks great to me!

2021-08-11 22:47 UTC, tas50 commented on content/ohai.md
> +Ohai collects data for many platforms, including AIX, Darwin, Linux, FreeBSD, OpenBSD, NetBSD, Solaris, and any Microsoft Windows operating systems.
```suggestion
Ohai collects data for many platforms, including AIX, macOS, Linux, FreeBSD, Solaris, and any Microsoft Windows operating systems.
```

2021-08-11 22:50 UTC, tas50 commented on content/ohai.md
>  - `:Sysctl` - All sysctl values on Linux hosts.
We're missing a one more here:

Grub2: Information from the Grub2 bootloader on Linux

2021-08-11 22:50 UTC, tas50 commented on content/ohai.md
>  ## ohai Cookbook Resource
```suggestion
## ohai Resource
```

2021-08-11 23:17 UTC, tas50 requested changes
I left a few suggestions

2021-08-11 23:53 UTC, tas50 approved these changes
ship it

2021-08-12 08:43 UTC, jonlives approved these changes

2021-08-12 22:01 UTC, IanMadd commented
I'm surprised the linter isn't freaking out about `themes/docs-new/layouts/shortcodes/cookbooks_content.md`, but I guess it doesn't check shortcodes.

2021-08-12 22:01 UTC, IanMadd approved these changes

2021-08-12 22:05 UTC, kagarmoe commented
@IanMadd I expected it to blow up, too.

2021-08-12 22:09 UTC, merged