Add more remote_file examples
chef/chef-web-docs pull request #3439
Opened 2021-09-23 00:58 UTC by tas50

Fill it out a bit more

Signed-off-by: Tim Smith <tsmith@chef.io>

2021-09-23 04:03 UTC, kagarmoe requested changes
Tiny change. Could you update the `file` resource next?

2021-09-23 04:03 UTC, kagarmoe commented on data/infra/resources/remote_file.yaml
> +      headers({ "Cookie" => "user=some_user; pass=p@ssw0rd!" })
```suggestion
      headers({ "Cookie" => "user=user_name; pass=p@ssw0rd!" })
```

2021-09-23 04:07 UTC, tas50 commented
These are the nast ones I've avoided automating in the past. When I get some time I'll slowly update other ones

2021-10-12 04:17 UTC, kagarmoe approved these changes
![tenor-232813978](https://user-images.githubusercontent.com/4400151/136890584-10436646-4830-4096-ae1b-c021d3cf0dc0.gif)

2021-10-12 04:19 UTC, merged