Update the System Requirement of Amazon Linux in Infra Server
chef/chef-web-docs pull request #3498
Opened 2021-10-20 13:33 UTC by dishanktiwari2501

## Description

Amazon Linux 2 is a supported platform that we test and it needs to be included on this page.

## Related PRs

- https://github.com/chef/chef-web-docs/issues/3376

2021-10-21 22:18 UTC, kagarmoe commented on themes/docs-new/layouts/shortcodes/adopted_platforms_server.md
> +<td>Amazon Linux 2</td>
We should list this in alphabetical order.

2021-10-21 22:19 UTC, kagarmoe requested changes
Thanks! Could you put the list into alphabetical order?

2021-10-22 11:38 UTC, dkumaras commented on themes/docs-new/layouts/shortcodes/adopted_platforms_server.md
> +<td>Amazon Linux 2</td>
done

2021-10-22 11:41 UTC, dkumaras commented
I thought I need to do, and just did a small change - @kagarmoe & @dishanktiwari2501

2021-10-27 19:06 UTC, kagarmoe approved these changes

2021-10-27 19:17 UTC, kagarmoe approved these changes

2021-10-27 19:18 UTC, kagarmoe approved these changes

2021-10-27 19:18 UTC, merged