Added EOL Warning to the ChefDK Release Notes
chef/chef-web-docs pull request #3557
Opened 2021-11-15 11:56 UTC by dishanktiwari2501

## Description

Added EOL Warning to the ChefDK Release Notes as the product is deprecated

## Related PRs

https://github.com/chef/chef-web-docs/issues/3459

2021-11-15 22:33 UTC, tas50 commented on content/release_notes_chefdk.md
> +{{% EOL_manage %}}
This is the wrong EOL warning.

2021-11-18 03:58 UTC, kagarmoe commented on content/release_notes_chefdk.md
> +{{% EOL_manage %}}
Yep, find or write the DK EOL

2021-11-18 03:59 UTC, kagarmoe requested changes
Look for the ChefDK EOL--you'll need to write one if it doesn't exist already.

2021-11-29 23:30 UTC, tas50 commented on themes/docs-new/layouts/shortcodes/EOL_chefdk.md
> +ChefDK is [deprecated](/versions/#deprecated-products-and-versions) and no
There's no need to contact an account rep. Users should download Chef Workstation, which includes all the functionality of ChefDK and a whole lot more.

2021-11-30 23:22 UTC, kagarmoe approved these changes

2021-11-30 23:27 UTC, merged