Update / refactor the Ohai docs a bit
chef/chef-web-docs pull request #652
Opened 2017-05-10 20:17 UTC by tas50

2017-05-11 17:10 UTC, thommay requested changes

2017-05-11 17:10 UTC, thommay commented on chef_master/source/chef_client.rst
> +       * Platform
As a casual reader, I can't really tell what `platform` might mean here. I think this bullet might be better written as "Operating System details"

2017-05-11 17:10 UTC, thommay commented on chef_master/source/ohai.rst
> +Ohai is a tool that is used to collect system configuration data, which is provided to the chef-client for use within cookbooks. Ohai is run by the chef-client at the beginning of every Chef run to d
"includes many built in plugins" ?

2017-05-11 17:10 UTC, thommay commented on chef_master/source/ohai_custom.rst
> +Loggging
i like your commitment to the letter 'g' here

2017-05-11 17:15 UTC, tas50 commented on chef_master/source/ohai_custom.rst
> +Loggging
We loggg a lot

2017-05-12 04:51 UTC, tas50 commented on chef_master/source/ohai.rst
> +Ohai is a tool that is used to collect system configuration data, which is provided to the chef-client for use within cookbooks. Ohai is run by the chef-client at the beginning of every Chef run to d
The updated wording work for you?

2017-05-12 04:51 UTC, tas50 commented on chef_master/source/chef_client.rst
> +       * Platform
Changed to Operating System

2017-05-12 09:13 UTC, thommay approved these changes

2017-05-12 15:42 UTC, tas50 commented
@davidwrede This is ready for merge now

2017-05-12 20:38 UTC, kagarmoe commented
![tenor-12262506](https://cloud.githubusercontent.com/assets/4400151/26016051/538535aa-3718-11e7-914c-99360e0ebc47.gif)

2017-05-12 20:39 UTC, merged