Adds steps for enabling TLS 1.3
chef/chef-web-docs pull request #790
Opened 2017-07-11 15:30 UTC by brewn

2017-07-11 15:30 UTC, brewn commented
#629

2017-07-14 17:39 UTC, juliandunn requested changes
Authentication protocol 1.3 is *not* a TLS version; it refers to the custom (Chef-developed) protocol that clients and servers use to sign their requests.

2017-07-14 17:41 UTC, juliandunn commented on chef_master/source/config_rb.rst
> +  Changed in Chef server 12.13 to expose FIPS runtime flag on RHEL.
I don't know what that means

2017-07-14 19:14 UTC, brewn commented on chef_master/source/config_rb.rst
> +  Changed in Chef server 12.13 to expose FIPS runtime flag on RHEL.
This was pulled in as part of a replication between the settings in the knife.rb documentation and those in config.rb, as the two were beginning to splinter, with knife.rb getting more updates. 

The "Changed in Chef server 12.13 to expose FIPS runtime flag on RHEL." line does seem like a non-sequitur here, though. I think it's meant to be a very roundabout way of saying that FIPS mode is only supported on RHEL (which is true but it also supports Oracle, CentOS and I think windows)...in other words that last sentence needs to be replaced.

2017-07-14 20:19 UTC, merged